Name="Make more, buy less"
Style="toner" # terrain, watercolor, toner 
MarkerColor="darkgreen" # red, blue, green, purple, orange, darkred, lightred, beige, darkblue, darkgreen, cadetblue, darkpurple, white, pink, lightblue, lightgreen, gray, black, lightgray
IconColor="black"
Zoom=8
MinZoom=6
MaxZoom=18
Symbols=[
    #Klasse:fontawesome symbol
    "Werkstatt:wrench",
	"Laden:shopping-basket",
	"Bank:money",
	"Lebensmittel:shopping-basket",
	"Elektronik:laptop",
	"Hackerspace:microchip",
	"Holzwerkstatt:tree",
	"Bastelmaterial:magnet",
	"Metallwerkstatt:cog",
	"Event:calendar",
	"Velowerkstatt:bicycle",
	"Restaurant:cutlery",
]
Center="Zürich"

